README.md
=> Fix link to tests in readme

bower.json
You may need to add a 0.13.4 git tag for this to work properly.
=> add bower.json for bower goodness

CHANGELOG.md
- From present back to 0.8.0 (after that it starts to get messy ;) )
=> Record changelog's past history

package.json, test/final-store.js, test/index.js, test/listen-to-actions.js, test/recorder.js, test/stores-get-alt.js, test/use-event-emitter.js
=> Use chai.assert

docs/testing/stores.md
- Remove example that relies too much on Alt's inner-workings
- Clean up some wording
=> Edit store testing docs

docs/createStore.md, src/alt.js, test/index.js
=> exportPublicMethods mixin

docs/stores.md
=> Explain static method magic in stores

docs/testing/stores.md
- User should be able to run this and see passing tests rather than having "approximate guidelines"
=> Update test store docs so example works

dist/alt-browser-with-addons.js, dist/alt-browser.js, dist/alt-with-runtime.js, dist/alt.js, src/alt.js, test/es3-module-pattern.js, test/helpers/SaaM.js, test/helpers/SampleActions.js, test/helpers/alt.js, test/store-as-a-module.js
This will allow you to create a store using a standard object.
There are some benefits to this approach:
You can use ES6 modules: https://gist.github.com/goatslacker/5a353916af65b3ee9987
You can use the ES3 Module pattern: https://gist.github.com/goatslacker/0f709f4436ed4890945d
And you can use other languages. This approach feels more flexible and less magical.
=> Allow creating stores from a POJO

dist/alt-browser-with-addons.js, dist/alt-browser.js, dist/alt-with-runtime.js, dist/alt.js, package.json
- If a user npm installed from prior package version they would still get this version of babel, which has some changes in compilation. This update ensures that everyone is on the current version to avoid confusion in `dist/` changes.
=> Update babel to latest version

components/AltContainer.js, dist/alt-browser-with-addons.js, dist/alt-browser.js, docs/components/altContainer.md, package.json, test/isomorphic-test.js, test/store-listener-component-test.js, web/_config.yml
This adds a component for store listening rather than relying on mixins.
=> Adds a store listener component

docs/immutable/immutablejs.md, docs/immutableExamples/immutablejs.md
- Add documentation on examples of using Immutable.js with alt
- Create folder structure to add more docs on using other immutable libs
=> Add immutable docs

README.md
It doesn't go anywhere!
Closes #154
=> Removed terse link

test/atomic-transactions-test.js, utils/atomicTransactions.js
Adds atomic transactions util for alt.
=> Adds atomic transactions

dist/alt-browser-with-addons.js, dist/alt-browser.js, dist/alt-with-runtime.js, dist/alt.js, docs/createStore.md, docs/lifecycleListeners.md, src/alt.js, test/before-and-after-test.js
Reverts goatslacker/alt#164
I didn't mean to get this in pre 0.16.0.
=> Revert "Before after lifecycle"

dist/alt-browser-with-addons.js, dist/alt-browser.js, dist/alt-with-runtime.js, dist/alt.js, docs/createStore.md, src/alt.js, test/es3-module-pattern.js, test/setting-state.js, utils/makeFinalStore.js
=> Make setState batch-able

dist/alt-browser-with-addons.js, package.json, src/alt-with-addons.js
Removes all the mixins and adds AltContainer + a few extras.
=> Shuffle the browser addons

components/AltContainer.js
=> Fix typo in comments

README.md
Utils were put into src folder
=> Updating utils links

components/AltContainer.js, components/mixinContainer.js, docs/components/altContainer.md, test/store-listener-component-test.js
=> Add `transform` function to AltContainer

docs/prepare.md, src/alt/AltStore.js, src/alt/index.js, test/index.js
Just a thought, we can call this function and have it return to us a serialized string ready for bootstrap. Could be useful if you have a chunk of data you want to load into a store.
=> Adds a prepare for bootstrap method to stores

docs/createStore.md, docs/lifecycleListeners.md, docs/serialization.md, src/alt/utils/StateFunctions.js, src/utils/ImmutableUtil.js, test/immutable-stores.js, test/index.js
This moves serialize/deserialize out of the lifecycle and to the store config.
Issue #198
=> Move serialize/deserialize to store config

.eslintignore, package.json, src/utils/TimeTravel.js, test/timetravel-test.js
#55 
Decorator for allowing time traveling on stores
=> Add a time travel decorator

examples/weathertabs/js/components/App.jsx, mixins/AltManagerMixin.js
Fix altmanagermixin to conform to new breaking changes in the call signature of createStore in 0.16.1. 
Also includes "bonus" fix to initially generate the correct weather for SF, CA.
=> Fix altmanager createstore call

guides/getting-started/async.md
Just a couple of minor typo fixes that I saw as I was reading the tutorial :)
=> Minor typo fixes

dist/alt-with-addons.js, dist/alt.js, src/alt/index.js, src/alt/store/index.js, src/alt/utils/AltUtils.js, src/utils/decorators.js, test/decorators-test.js
Adds support for some fancy decorators with alt
=> Fun with more decorators

src/alt/index.js, src/alt/store/AltStore.js, src/alt/store/StoreMixin.js, src/alt/store/index.js, src/alt/symbols/symbols.js, src/alt/utils/StateFunctions.js
=> Makes the lifecycle methods eventemitters

docs/utils/immutable.md
per the comment I made in gitter.
=> typo in immutableUtil docs

guides/getting-started/view.md
I expect a lot of issues merging this
=> Update connectToStores ref in docs

examples/todomvc/package.json, examples/weathertabs/package.json
Need to build Alt before. (root)
=> Fix npm build examples

dist/alt-with-addons.js, dist/alt.js, src/alt/store/StoreMixin.js, test/async-test.js
Pass in arguments that DataSource method was called with to intercept as an array
=> Update DateSource intercept to recive method args

src/utils/fp.js, test/functional-tools-test.js
Adding some functional utilities for stores
=> Functional tools

src/alt/index.js, test/batching-test.js
=> Adding a batching function for the dispatcher

src/alt/index.js
Adds support for a batchingFunction though optional config. To be used with React.addons.batchedUpdates
Still needs tests.
=> Add batchingFunction support for Flux Dispatcher

examples/todomvc/js/components/TodoItem.react.js, examples/todomvc/js/stores/TodoStore.js
https://github.com/goatslacker/alt/issues/326
=> fix todo item text update bug (examples/todomvc)

docs/async.md
Added some possibly helpful pieces to the async doc for sources around required/optional methods, loading method, and ways to always fetch remotely.
Closes goatslacker/alt#350
=> Added more clarity for implementing sources in async doc

src/utils/AltIso.js, src/utils/Render.js, test/alt-iso-browser-test.js, test/alt-iso-test.js
=> Add failing AltIso test

dist.config.js, dist.min.config.js, package.json
I did not add new dist/*js files. They have to be regenerated and added to repo.
=> replace  browserify with webpack for bulding dist/

CHANGELOG.md
=> Fix DispatcherDebugger commit link in changelog

docs/async.md
=> explain how to use methods from sources

README.md
Added under examples but we can even create a separate heading eg. usecases or companies using Alt or anything else
=> This article tells a very good story of why Alt  over other flux frameworks

docs/createActions.md
Clarified the return-to-dispatch semantics, and its exceptions. Added examples.
=> Update createAction docs

src/alt/store/StoreMixin.js
This enables data sources to be used as promise chains without having to do cumbersome conditionals to check whether the data source method will return a Promise or undefined. Currently any value returned from `local` will never be return to the caller.
That fact is a big issue as promise based workflows, such as having to load certain things in order, become cumbersome to write. Consider this:
```
let firstNotification, author;
NotificationStore.fetch().then(() => {
firstNotification = NotificationStore.first();
return UserStore.find(firstNotification.user_id);
}).then(() => {
// Yay we're done;
});
```
If the data source's `shouldFetch` returns false, then this chain breaks immediately. Given that the lack of a return statement and unspecified behaviour I wouldn't consider this a …
=> Return local's value rather than undefined

src/alt/store/StoreMixin.js
Not important change, just less lines (and maybe slightly more performant?)
=> Make the IFs less verbose on BindActions

README.md, docs/typescript.md, typings/alt/alt-tests.ts, typings/alt/alt.d.ts
…e, type generics now pass to sources, exported ghost module with other helpful interfaces. Test file required for definitely-typed repo included in typings directory, basic docs and usage added
=> Cleaned up defs, added typing to Sources, added test file and docs, cleaned up Readme.

README.md
I've created a generator for that boilerplate as I find it easier for people to use and it kind of _deprecated_ the boilerplate (that will be used for experimentation now, not as a base for developing).
=> Update link from boilerplate to generator

docs/components/altContainer.md
The use of props is never explained in the doc and the code is incorrect.
=> The use of 'props' needs explaination

guides/getting-started/async.md
- Remove `this.dispatch` in favor of returning a thunk.
- `this.actions.doSomething()` -> `this.doSomething()`
=> Update Fetching Data docs for 0.18

docs/createActions.md
=> Update createActions docs

src/actions/index.js, test/async-action-test.js
=> Fix failing Promises example from the documentation.

src/index.js, src/store/StoreMixin.js, test/async-test.js
Reverts goatslacker/alt#522
Reverting to have a clean master to release from. Plus I want to move data sources more evenly out to npm.
=> Revert "Removes data sources"

guides/getting-started/actions.md
`this.dispatch` no longer exists, having it in the docs is confusing.
=> Remove reference to this.dispatch

src/utils/AltUtils.js
=> Fix inheritance of actions
