goatslacker/alt

src/alt.js

without this there can be for example only one action named 'update'.
with this you can have multiple ActionClasses with same actions.
class UserActions {
constructor() { this.generateActions('update'); }
}
module.exports = alt.createActions(UserActions);
class LinkActions {
constructor() { this.generateActions('update'); }
}
module.exports = alt.createActions(LinkActions);

Allow same action name on diffrent ActionClasses

---

README.md
dist/alt-with-runtime.js
dist/alt.js
src/alt.js
test/index.js

If you're not opposed to overloading the API, I think it could be useful to implement a shorthand for `alt.createActions()` that accepts an array of action names and automatically calls `this.generateActions()` for you in the constructor.
This pull request makes it so that the following two snippets are equivalent:
```javascript
var mySimpleActions = alt.createActions(['actionOne', 'actionTwo', 'actionThree'])
```
---
```javascript
class MySimpleActions {
constructor() {
this.generateActions('actionOne', 'actionTwo', 'actionThree')
}
}
var mySimpleActions = alt.createActions(MySimpleActions)
```
Something to consider is that there would be an inconsistency between `generateActions` accepting multiple arguments and `createActions` accepting an array. Using a spread operator on the first …

Adding a shorthand form of alt.createActions()

---

dist/alt-with-runtime.js
dist/alt.js
src/alt.js
test/index.js

Will also accept multiple params instead of only an array of items. Backwards compatible with Facebook's version of waitFor().
As discussed in #38

Updated .waitFor() to allow passing store instances instead of tokens. 

---

bower.json
dist/alt-browser-with-addons.js
dist/alt-browser.js
package.json
src/alt-with-addons.js

Uses browserify and babelify to assemble a bower-friendly standalone
version of Alt.
Updated bower's `main` to use the browser version, removed bower
dependencies block as they are now longer needed.

Enable browser builds.

---

docs/testing/stores.md

Solves Issue #45. Sets up folder in docs for testing documentation.

Add store testing documentation

---

README.md
docs/bootstrap.md

- Docs reference that bootstrap can only be done once, which is no  longer true thanks to this commit 0ba7b85
- Fix a few spelling mistakes in README

Update bootstrap docs

---

dist/alt-browser-with-addons.js
dist/alt-browser.js
dist/alt-with-runtime.js
dist/alt.js
docs/lifecycleListeners.md
docs/serialization.md
src/alt.js
test/index.js

- `deserialize` is called before bootstrap/snapshot data is set back to the store. this allows the data to be transformed into a format that  the store expects. the return data becomes the store's state.
- `snapshot` now allows an optional return value. this value is used as the snapshot data if provided, otherwise the default `Store#getState()` is used.
- see the docs for more information

Add deserialize lifecycle hook

---

dist/alt-browser-with-addons.js
dist/alt-browser.js
dist/alt-with-runtime.js
dist/alt.js
package.json
src/alt.js
utils/AltTestingUtils.js

- Update to latest version of eslint with much better es6 support. We no longer will need `babel-eslint`
- Fix all linting errors

Update eslint and fix linting errors

---

dist/alt-browser-with-addons.js
dist/alt-browser.js
dist/alt-with-runtime.js
dist/alt.js
src/alt.js
test/index.js
test/recorder.js
utils/DispatcherRecorder.js

This allows the serialization/deserialization of events when using the dispatcher recorder. Now it's able to intercept events and fire off actions later in separate alt apps even (provided the same code is running).

Adds serialize/loadEvents to dispatcher recorder

---

dist/alt-browser-with-addons.js
dist/alt-browser.js
dist/alt-with-runtime.js
dist/alt.js
docs/bootstrap.md
src/alt.js
test/index.js

Should we always emit an event automatically on bootstrap, recycle, and flush?

Always emit a change

---

README.md
dist/alt-browser-with-addons.js
dist/alt-browser.js
dist/alt-with-runtime.js
dist/alt.js
docs/takeSnapshot.md
src/alt.js
test/index.js

- This enables snapshotting a subset of the app data
- `takeSnapshot` returns stringified JSON containing just the subset of data specified. The new snapshot is merged with the `LAST_SNAPSHOT` data to ensure that the last snapshot of the stores not specified in the subset is not lost. This also means that rollbacks will just work.
- Resolves Issue #54

Allow `takeSnapshot` to specify stores

---

dist/alt-browser-with-addons.js
dist/alt-browser.js
dist/alt-with-runtime.js
dist/alt.js
src/alt.js
test/index.js

- first snapshot works, but any snapshots after that are not correctly set
- `snapshot` returns stringified json, so in order to use assign, we must first parse the stringified json so that the state merges correctly
- add a test so this issue is checked in the future

Fix subsequent snapshots

---

dist/alt-browser-with-addons.js
dist/alt-browser.js
dist/alt-with-runtime.js
dist/alt.js
src/alt.js
test/bound-listeners-test.js
test/store-model-test.js

This opens the door for a couple of things:
Having direct access to the store model constructor makes for nice and easy testing (no more double exports) and it also makes for better introspection.
Having the names of the subscribed listeners is good for introspection.
These are properties rather than functions because I see no reason to hide them and mutating them shouldn't have terrible consequences.

Add store instance properties

---

web/.gitignore
web/Gemfile
web/Gemfile.lock
web/README.md
web/Rakefile
web/_config.yml

- Enables use of docs/, guides/ folders from master branch. Just
converts the links into the format the web expects.
- Website work is still done on master branch. Rake task is used to
deploy latest changes to gh-pages branch.
- Sets up Jekyll such that development can be done locally to ensure
that the site looks correct before deploying to gh-pages.
- Once this is merged in, we just need to run the deploy task and we will have our gh-pages branch set up and ready to go!

Setup tasks to build gh-pages site

---

package.json

Windows needs the full path for Istanbul to run _mocha.  Should be ok across platforms, may want to test.

script update to run istanbul; windows compatibility

---

dist/alt-browser-with-addons.js
dist/alt-browser.js
dist/alt-with-runtime.js
dist/alt.js
docs/altInstances.md
src/alt.js
test/alt-config-object.js

- alt constructor takes config object that enables user to override defaults, in this case the dispatcher
- If dispatcher has interface with waitFor, dispatchToken, register, and dispatch functions, then it is valid and can be used, otherwise the default FB dispatcher is used as fallback
- This PR sets up a clean infrastructure to allow users to override other alt defaults
- Solves Issue #106

Allow custom dispatcher to be specified

---

guide/store.md

Add a comment in the example action handler code about the optional ability to suppress the store change event after the action handler ends.

Guide: change event suppress comment in store.md

---

README.md

In the README add the alternative approach of using exportPublicMethods in a store.

Add note about exportPublicMethods in README

---

dist/alt-browser-with-addons.js
dist/alt-browser.js
dist/alt-with-runtime.js
dist/alt.js
docs/altInstances.md
src/alt.js
test/alt-config-object.js

- By default alt uses JSON.stringify/JSON.parse. This change allows the config object to provide custom serialization/deserialization functions to be used in their place
- Resolves Issue #105

Allow serialize/deserialize functions to be specified by config

---

components/AltContainer.js

Currently it throws 
```
AltContainer.js:107 Uncaught SyntaxError: Unexpected token (
```
when using AltContainer.
Another option would be to add 
```
"browserify": {
"transform": [
"babelify"
]
},
```
to package.json

fix AltContainer using ES6 concise function

---

docs/components/altContainer.md

`AltContainer` doesn't seem to be exported through the main file. Was it meant to be an optional part of the core?

Added documentation for importing AltContainer.

---

README.md
dist/alt-browser-with-addons.js
dist/alt-browser.js
dist/alt-with-runtime.js
dist/alt.js
docs/lifecycleListeners.md
src/alt.js
test/failed-dispatch-test.js

This adds a try/catch to alt's dispatch for purposes of allowing you to catch errors in the store.
If your store class contains a `failedDispatch` method you'll receive the error and then you can deal with it.
This opens the door for better rollbacks/atomic transactions.
If the store does not contain a failedDispatch method then the error throws so it is not swallowed.
Adds ~11 LOC to alt core.
My only concern is that now every dispatch call is wrapped in a try/catch.
Thoughts?

Catch errors in stores

---

README.md

Added missing `function` keyword, since in its current form it only works with an ES6 transpiler.

README: Added "function" to regular old JavaScript code

---

dist/alt-browser-with-addons.js
dist/alt-browser.js
dist/alt-with-runtime.js
dist/alt.js
src/alt.js
test/index.js
test/stores-get-alt.js
utils/makeFinalStore.js

Alt's first breaking change.
I'm thinking we should be able to pass in custom items into the store and actions constructors so this would make the following changes:
`alt.createStore` just takes a StoreModel and a name, all other arguments are passed to the store's constructor.
`alt.createActions` takes in the ActionsClass, an optional object to export actions to, all other args are passed to the action's constructor.
`alt.addActions` is name, class, and ...args
`alt.addStore` is name, class, and ...args
This removes the saveStore boolean that was previously present for addStore and createStore, if you wish to create a store that will not be part of bootstrapping then a new method `alt.createUnsavedStore` has been added.
The other breaking change is that actions and stores no longer have …

Allow passing in args to store and actions constructors

---

dist/alt-browser-with-addons.js
dist/alt-browser.js
dist/alt-with-runtime.js
dist/alt.js
src/alt.js
test/custom-state-key-test.js

Lets have our :cake: and eat it too.
This PR adds a way out of #158 where we can get the best of both worlds. Through alt's config object you can specify a state key where your state will live:
```js
const alt = new Alt({ stateKey: 'bears' })
class Foo {
static displayName: 'FooStore'
constructor() {
this.lookThisIsPrivate = 'yes it is'
this.bears = {
state1: 1,
state2: 2
}
}
}
```

Allow customizing your state property key

---

package.json
src/alt/AltStore.js
src/alt/index.js
src/alt/utils/StoreUtils.js
src/alt/utils/createStoreConfig.js
src/utils/ImmutableUtil.js
test/babel/index.js
test/immutable-stores.js

Playing with this API, I think it's way nicer than the current one.
Thoughts @ziflex @jdlehman

Immutable decorator

---

src/utils/withAltContext.js
test/store-listener-component-test.js

This makes withAltContext a decorator.
New API:
```js
@withAltContext(flux);
class App extends React.Component {
render() {
return (
// things in here get the flux context
)
}
}
```
or
```js
class App extends React.Component { }
module.exports = withAltContext(flux)(App)
```

withAltContext as decorator

---

dist/alt-with-addons.js
dist/alt.js
package.json
src/alt/AltStore.js
src/alt/utils/StoreUtils.js
src/utils/ImmutableUtil.js
test/immutable-stores.js

Fixes #212 
The problem was that `this.state` was referencing the original Immutable object, so any subsequent mutations would result in the original object + whatever mutations you just made. This means that if you did five consecutive mutations only the first and last would apply.
The solution was to pass in the context of `this` to setState and getState so I'm able to poke into the store and update `this.state` so you're able to re-use it.
I've added both test cases from #212 as well.

Fixes immutable util for subsequent mutations

---

src/alt/AltAction.js
src/alt/index.js
src/alt/utils/makeAction.js
src/utils/ActionListeners.js
test/listen-to-actions.js

Fixes #192 we pass in a whole slew of details through the dispatch.
For this action class:
```js
class MyActions {
static displayName = 'MyActions'
updateName(name) { this.dispatch(name) }
}
```
we would get this info:
```js
details: {
namespace: 'MyActions',
name: 'updateName',
id: 'MyActions.updateName',
symbol: Symbol('alt/MyActions.updateName')
}
```
you can extra it via `payload.details`.

Pass action details through the dispatch

---

components/AltContainer.js
components/AltNativeContainer.js
components/mixinContainer.js
dist/alt-with-addons.js
dist/alt.js
package.json
src/alt/index.js
src/alt/store/AltStore.js
src/alt/store/StoreMixin.js
src/alt/store/index.js
src/alt/utils/AltUtils.js
src/alt/utils/StateFunctions.js
src/utils/AltTestingUtils.js
src/utils/TimeTravel.js
src/utils/atomic.js
src/utils/connectToStores.js
src/utils/decorators.js
src/utils/functions.js
test/helpers/ReactComponent.js
test/store-model-test.js

object-assign uses the Object.assign polyfill if available. react-native has its own stupid polyfill which. We are abusing Object.assign sometimes and hitting some of the "edge cases" that react-native's polyfill doesn't support for perf reasons. So lets just do forego the Object.assign polyfill and have our own. Bonus points: it makes our build smaller.

Make our own assign

---

src/utils/decorators.js
test/decorators-test.js

Fixes #244 
API:
```js
class TodoStore {
constructor() {
this.todos = []
}
@bindWithContext(alt => alt.actions.TodoActions.addTodo)
addTodo(item) {
this.todos.push(item)
}
}
class Flux extends Alt {
constructor() {
super()
this.addActions('TodoActions', [
'addTodo'
])
this.addStore('TodoStore', decorate(this)(TodoStore))
}
}
```

decorators for instances

---

src/utils/connectToStores.js
test/connect-to-stores-test.js

This allows for: 
```
statics: {
getStores(props) {
return [
props.flux.stores.SearchStore
];
},
getPropsFromStores(props) {
return props.flux.stores.SearchStore.getState();
}
}
```

Allow connectToStore components to use props in getStores

---

dist/alt-with-addons.js
dist/alt.js
docs/async.md
src/alt/store/StoreMixin.js
test/async-test.js

If shouldFetch returns true, it will always call remote to get the value, and if it returns false, it will always use the local value. If it is not defined, the presence of the local value determines if remote is called or not.
#257

Allow shouldFetch function in data source for async calls

---

src/alt/utils/StateFunctions.js
test/recycle-test.js

This fixes a bug where recycle used to merge state so if the keys were not being overwritten then some old state would remain.
This affected rollbacks, recycle, and bootstrap.

Fix recycling values that are not set

---

docs/async.md
src/alt/store/StoreMixin.js
test/async-test.js

Fixes isLoading call if multiple requests are in-flight.
Given the nature that the status is reset every time a new call is made a situation may arise where the isLoading boolean is prematurely set to false. Changing this to a counter fixes the issue.
cc @wlue

Fix isLoading for multiple async calls

---

README.md

**What**
I updated the link to API reference from [https://goatslacker.github.io/alt/](https://goatslacker.github.io/alt/) to [http://alt.js.org/docs/](http://alt.js.org/docs/)
**Why**
The current address links to the site with broken styles (tested on Linux with FF 38 and Chromium 43 with and without extensions) - it seems that's the same page as [the official one](http://alt.js.org/) but without any styles (maybe that's the problem on my end?). But I guess it's also good to have consistent URLs in the project.
**Post Scriptum**
I love `alt` :)

Update link to API Reference

---

bower.json

Changes:
- Bower will now serve 0.16.6 as the `bower install` default

Update Bower package to 0.16.6

---

README.md

For those of us who dwell more on the READMEs than the actual project site, a mention to the existence of the getting started guide can be quite helpful.

Include a reference to the Getting Started guide in the README

---

dist/alt-with-addons.js
dist/alt.js
src/alt/index.js
test/debug-alt-test.js

Adding the chrome debugging to alt core. I'd like to probably add this in as a patch and then remove the chromeDebug util for 0.17.0
This would support multiple alt instances

Add debug to alt

---

README.md

[Maple](https://github.com/Wildhoney/Maple.js) uses Alt.js in its example for webcomponents in React &ndash; with an [example up and running on Heroku](http://maple-app.herokuapp.com/).

Using Alt.js in Maple example

---

README.md

Very similar (as this was motivated by) to @voronianski's [Shopping Cart](https://github.com/voronianski/flux-comparison/tree/master/alt). But this one uses ImmutableJS (for the stores, naively), and extends its features.
\* Uses Alt `v0.15.x`

Added "Jumar's Tindahan" to the examples

---

src/alt/store/AltStore.js
src/alt/store/index.js
test/async-test.js
test/es3-module-pattern.js
test/functional-test.js
test/index.js

Brings in a lot of the ideas of [microflux](https://github.com/goatslacker/microflux) into Alt.
This PR is full of new features:
* preventDefault() is this new method available on the store that will prevent a change event from being emitted. This is a better alternative than returning false from each action handler as this is more explicit. This will also be needed for other methods below.
* observe() is a new method that you define in your store. It was made mostly for when creating stores with POJOs and using alt instances. This method gets `alt` as its first and only parameter and you return an Object from it. The Object contains the same stuff that would go in `bindListeners`. These listeners are then bound.
* otherwise() is a new method you define in your store. This is a concept …

Add FP goodies baked into alt

---

.eslintrc
dist/alt-with-addons.js
dist/alt.js
src/alt/store/StoreMixin.js
src/utils/AltIso.js
src/utils/Render.js
test/alt-iso-browser-test.js
test/alt-iso-test.js
test/async-test.js

There's some clean up work I'd still like to do with this but I'm throwing it up here for now to gather early feedback/let people know what's coming.
Why?
It allows us to define our data fetching needs in the component. It's not quite relay though, you don't define what you need but rather how you're going to get it.
This works very well with Alt's [Data Sources](http://alt.js.org/docs/async/).
This lets you keep your singleton stores and actions which are easier to reason about and you don't have to pass flux around in context.

The holy-grail of server rendering

---

guides/es5/index.md

I had to dig around to figure out that a "publicMethods" property could be defined when using the object syntax.  I added this to the es5 guide for anyone else looking for this.  While I was at it, I added examples of the other methods as well.

Add some notes in the documentation about how to create public store methods using es5 syntax. 

---

bower.json

Stop leaving us lowly Bower users out in the cold after the version bump. ;)
Changes:
- Bower will now serve 0.16.9 as the `bower install` default

Update Bower package to 0.16.9

---

dist/alt-with-addons.js
dist/alt.js
src/utils/connectToStores.js
test/connect-to-stores-test.js

I added an API for component did connect, I am not sure if this was where you wanted it in the source, not quite sure how to ensure it makes it into the decorator. Let me know if you want me to change it.

Component did connect hook

---

README.md

I've added a React Native example application to the examples list.
The application renders the most recent tweets for a given location and was built using React Native with an Alt Flux implementation. 
You can see the repo [here](https://github.com/mrblueblue/react-native-alt-demo)

Update README with React Native example

---

bower.json

* Fixes broken reference to /dist/alt-browser.js, replacing it witth /dist/alt.js
close #321

fix broken reference to /dist/alt-browser.js

---

docs/altInstances.md

The Markdown renderer in GitHub seems to accept triple backticks without an empty line above.  The one that generates the site doesn't.

Adding an empty line before a code section

---

src/utils/AltTestingUtils.js

Add exportAsync and registerAsync noop functions, missing from AltTestingUtils.
Closes #397

Add async functions to AltTestingUtils

---

docs/utils/immutable.md

After I fixed the `properties` that should be `prototype` I found that `this.setState(this.state.todos.set(id, todo));` was wrong. That ends up replacing `this.state` with the modified version of `this.state.todos`. I have no prior experience with Alt, this is just the solution I backed into while trying to figure out and fix the `this.setState` call. Since "Alt has first-class support for immutable data structures via the ImmutableUtil" it does feel like I'm missing a better solution.

Fix ImmutableUtils docs

---

guides/es5/index.md

`pubilcMethods` -> `publicMethods`

Fix typo in guides

---

src/utils/connectToStores.js
test/connect-to-stores-test.js

This makes using instances of alt by passing them through React context easier. StoreConnection doesn't have any contextTypes defined, so when it calls getStores/getPropsFromStore and passes in props/context, context will always be empty. To fix this, we can copy the contextTypes your component would've received, if it weren't wrapped, onto StoreConnection itself.

Copy child context types when creating storeconnection

---

src/alt/actions/index.js
src/alt/index.js
src/alt/store/AltStore.js
src/alt/utils/AltUtils.js
test/index.js

This allows the use of action creators which is good for using instances since now you can import actions directly and then just dispatch them.
```js
const increment = {
id: 'my/increment/action',
dispatch(x) {
return x
}
}
alt.dispatch(increment, 2) // will call my/increment/action with a payload of 2
```

Allow dispatching actions with action creators

---

src/alt/store/index.js
src/alt/utils/StateFunctions.js
src/utils/ImmutableUtil.js
src/utils/functions.js
test/atomic-transactions-test.js
test/es3-module-pattern.js
test/immutable-stores.js
test/store-listener-component-test.js
test/value-stores-test.js

When using a store that has state that is a value and not an object we still want to be able to use this.setState

Fix setState so it handles values

---

README.md

Please include generator-react-webpack-template to the boilerplates section of the README.

Add generator-react-webpack-alt to boilerplate section

---

.npmignore

Because there are different versions that contain different schema for a .babelrc file, it's probably best to avoid keeping this file in version control.

remove babelrc

---

docs/testing/actions.md
guides/es5/index.md
guides/getting-started/actions.md
web/_posts/2015-01-22-how-to-convert-flux-to-alt.md

Together with #570 and #571, all usages of `this.dispatch` in the docs should be updated to use the new 0.18 syntax.

Remove this.dispatch usage from docs

---

README.md

I noticed that since installing 0.18.1 that the utils have now been removed.
The documentation has fallen behind a little with regards to the `View` section when it comes `connectToStores` so I have updated to let users know to install the `alt-utils` package and get connectToStores from there.
Also, when I was trying to use alt.js for the first time I was having problems with the fact the View example was using the ES7 `@connectToStore` decorator which really threw me off as I hadn't looked at any ES7 features and had no idea what to search for to find why it wasn't working for me.  So I updated it to include ES6 and ES7 examples

Updating documentation on connectToStores alt util

---

docs/takeSnapshot.md

I thought this might be useful for newcomers to alt, as it shows the relation between the two methods.
Open to suggestions on how to improve this though.

Linking to bootstrap doc page from takeSnapshot

---

package.json

After checking out the source code for the first time and `npm install` the error was being displayed:
The reason was a missing `babel-loader` and `style-loader` dependency. This should be gone with this PR merged in.

Fix dev deps so that the build doesn`t break after the initial setup.

---

.babelrc
package.json

Starting with Babel 6 and onwards, Babel [no longer exports](http://stackoverflow.com/a/34778391/596625) libraries under `module.exports` which is breaking our builds. There's a neat plugin that fixes the behavior.

Fix module exports.

---

README.md

This removes a pair of broken links to examples that no longer exist in this repository. These examples were removed in this commit https://github.com/goatslacker/alt/commit/f365116db93b899f92c676eebfc21a167655c5d1

Remove broken example links from README

---

typings/alt/alt.d.ts

Apparently new Alt version ( 0.18.x ) removed `dispatch` from Actions.

Removed dispatch from typings

---

README.md

Updated link to boilerplate as react-webpack-node now has their alt implementation on a branch.

Updated link to boilerplate
